export const CHARACTER_LIMIT = 25000;
export const MAX_PRODUCTS_PER_REQUEST = 100;
export const REQUEST_TIMEOUT = 30000; // 30s
export const MAX_ORDERS_TO_FETCH = 1000;
export const MAX_DATE_RANGE_DAYS = 730; // 2 years
export const MAX_CONCURRENT_REQUESTS = 5;

export const PRESTASHOP_ERROR_CODES = {
  AUTH_FAILED: 'AUTH_FAILED',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  INVALID_DATE_RANGE: 'INVALID_DATE_RANGE',
  API_RATE_LIMIT: 'RATE_LIMIT',
  NETWORK_TIMEOUT: 'TIMEOUT',
  RESPONSE_TOO_LARGE: 'RESPONSE_TOO_LARGE',
} as const;
